apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deploy
  labels:
    app: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: java-app
        image: hc0211/test:latest
        ports:
        - containerPort: 8080
